//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_COMPANY_RELATION_HIS
    {
        public string aply_no { get; set; }
        public string relation_id { get; set; }
        public string exec_action { get; set; }
        public string b_reciept_type { get; set; }
        public string b_company_code { get; set; }
        public string b_payment_type { get; set; }
        public string b_currency_code { get; set; }
        public string b_is_disabled { get; set; }
        public string a_reciept_type { get; set; }
        public string a_company_code { get; set; }
        public string a_payment_type { get; set; }
        public string a_currency_code { get; set; }
        public string a_is_disabled { get; set; }
        public string apply_status { get; set; }
        public string appr_id { get; set; }
        public Nullable<System.DateTime> appr_datetime { get; set; }
        public string apply_id { get; set; }
        public Nullable<System.DateTime> apply_datetime { get; set; }
    }
}
