//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_COMPANY_CODE
    {
        public string company_code { get; set; }
        public string company_name { get; set; }
        public string company_vat_no { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string appr_id { get; set; }
        public Nullable<System.DateTime> appr_datetime { get; set; }
        public string disable_id { get; set; }
        public Nullable<System.DateTime> disable_datetime { get; set; }
        public string is_disabled { get; set; }
    }
}
